---
language: python
python: ["2.7", "3.5"]
dist: trusty
sudo: True
group: beta
env:
    global:
        - VBOX_MEMORY=2048
    matrix:
        - TOXENV=pre-commit
        - TOXENV=openbsd60
        - &openbsd59 TOXENV=openbsd59
        - TOXENV=xenial
        - TOXENV=trusty
        - TOXENV=precise
        - &stretch TOXENV=stretch
        - TOXENV=jessie
        - TOXENV=wheezy
matrix:
    fast_finish: True
    allow_failures:
        - python: "3.5"
        - env: *openbsd59
        - env: *stretch
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

install:
  - sudo apt-get update
  - sudo apt-get install -y linux-headers-$(uname -r) virtualbox
  - wget https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb
  - sudo dpkg -i vagrant_1.9.1_x86_64.deb
  - pip install tox | cat

script:
  - travis_wait 45 tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
  on_failure: never
